services:
  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    networks:
      - traefik-internetwork
    volumes:
      - grafana_storage:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-internetwork"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  traefik-internetwork:
    external: true

volumes:
  grafana_storage:
    external: true
